In [1]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
A = array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
M = mean(A.T , axis=1)
print(M)

[3. 4.]


In [4]:
C = A-M
print(C)

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


In [5]:
V=cov(C.T)
print(V)

[[4. 4.]
 [4. 4.]]


In [6]:
values, vectors=eig(V)
print(values)

[8. 0.]


In [7]:
P=vectors.T.dot(C.T)
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [8]:
from sklearn.datasets import fetch_mldata

In [9]:
from sklearn import datasets
digits = datasets.load_digits()

In [10]:
digits.data #PCA is applied on feature vector

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [12]:
digits.target #class labels

array([0, 1, 2, ..., 8, 9, 8])

In [13]:
from sklearn.model_selection import train_test_split
train_img, test_img, train_lbl, test_lbl= train_test_split(digits.data, digits.target,test_size=0.25, random_state=0)

In [14]:
from sklearn.decomposition import PCA # make an instance of the model
pca = PCA(.95)

In [15]:
pca.fit(train_img)

PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [16]:
pca.n_components_

28

In [17]:
train_img.shape

(1347, 64)

In [18]:
train_img = pca.transform(train_img)
test_img = pca.transform(test_img)

In [19]:
train_img.shape

(1347, 28)