In [ ]:
# Rutuja Bhandigani
#PB55 PANEL 2
# PRN: 1032170889


In [12]:
#Importing Required Libraries
import numpy as np
import pandas as pd
import sklearn
from sklearn.neighbors import KNeighborsClassifier
#Reading the dataset
dataset = pd.read_csv("knn.csv")
x = dataset.iloc[:,:-1].values #features
y = dataset.iloc[:,2].values #target

In [13]:
#Using KNN
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x,y) #training
x_test = np.array([4,2])
y_predict=classifier.predict(x) #testing
print(y_predict)
#Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y,y_predict)

['N' 'N' 'N' 'P' 'P' 'N']


array([[2, 2],
       [2, 0]], dtype=int64)

In [14]:
#Assigining features and label variables
#First Feature
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']

# Second Feature
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

# Label or target varible
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [15]:
#Import LabelEncoder
from sklearn import preprocessing
#Creating LabelEncoder
le = preprocessing.LabelEncoder()
#Converting weather strings labels imto numbers 
weather_encoded = le.fit_transform(weather)
print(weather_encoded)
#Converting temp string labels into numbers
temp_encoded = le.fit_transform(temp)
#Converting play string labels into numbers
label = le.fit_transform(play)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [16]:
#Combining weather and temp into single list of tuples
features = list(zip(weather_encoded,temp_encoded))

In [17]:
#Using KNN
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
#Train the model using training sets
model.fit(features,label)
#Predict output
predicted = model.predict([[0,2]]) #0: Overcast 2:Mild
print(predicted)

[1]


In [18]:
#For Regression
from sklearn.neighbors import KNeighborsRegressor
#Reading the dataset
dataset=pd.read_csv("knn1.csv")
x=dataset.iloc[:,:-1].values #features
print(x)
y=dataset.iloc[:,2].values #target
print(y)

[[ 5.   45.  ]
 [ 5.11 26.  ]
 [ 5.6  30.  ]
 [ 5.9  34.  ]
 [ 4.8  40.  ]
 [ 5.8  36.  ]
 [ 5.3  19.  ]
 [ 5.8  28.  ]
 [ 5.5  23.  ]
 [ 5.6  32.  ]]
[77 47 55 59 72 60 40 60 45 58]


In [19]:
#Using KNN
classifier = KNeighborsRegressor(n_neighbors=5)
classifier.fit(x,y) #training
x_test = np.array([5.50,26])
y_predict = classifier.predict([x_test])  #testing
print(y_predict)

[53.]


In [21]:
#Accuracy Score
from sklearn.metrics import accuracy_score
y_predict = classifier.predict(x)
accuracy_score(y, np.round(y_predict), normalize=True)

0.1